title = "Southam Law"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"

  [menu]

    [[menu.header]]
      weight = 2
      name = "Success stories"
      url = "success"
    [[menu.header]]
      weight = 3
      name = "News"
      url = "news"
    [[menu.header]]
      weight = 4
      name = "Services"
      url = "services"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "work"
    [[menu.footer]]
      weight = 4
      name = "News"
      url = "news"
    # [[menu.footer]]
    #   weight = 5
    #   name = "Terms"
    #   url = "#"

  [params.header]
    bgImage = "images/depaul-loop-trimmed.jpg"
    bgImage500 = "images/depaul-loop-trimmed-500.jpg"
    bgImage1000 = "images/depaul-loop-trimmed-1000.jpg"
    bgImage2000 = "images/depaul-loop-trimmed-2000.jpg"
    bgImage3000 = "images/depaul-loop-trimmed-3000.jpg"
    bgImage4000 = "images/depaul-loop-trimmed-4000.jpg"

  [params.slider]
    enable = true
    title = "Understand Your Case. Keep Costs Down."
    subtitle = "Immigration law is frustratingly complex and rapidly changing. Southam Law LLC strives to help you understand what is happening in your case and why. We take the time to explain the law and the facts of your case in everyday terms. At the same time, Southam Law keeps costs down. We never bill by the hour, and our costs are clear upfront. We also offer levels of service for different budgets."
    bgImage = "images/depaul-loop.jpg"
    bgImage500 = "images/depaul-loop-500.jpg"
    bgImage1000 = "images/depaul-loop-1000.jpg"
    bgImage2000 = "images/depaul-loop-2000.jpg"
    bgImage3000 = "images/depaul-loop-3000.jpg"
    bgImage4000 = "images/depaul-loop-4000.jpg"
    btnText = "See the services we offer"
    url = "/services"

  [params.news]
    enable = true
    title = "Read about recent updates with the office and immigration law"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We fight for immigrants and families"
    # bgImage = "images/depaul-loop.jpg"
    content = "A main goal of Southam Law LLC is to ensure that you understand how immigration law affects your unique situation. Unlike other law offices, Southam Law LLC takes the time to explain the choices you have so that you can make informed decisions about your case. Southam Law LLC also recognizes that another barrier is cost. Lawyers are expensive, and frequently the final costs are not clear in advance. In virtually all cases, Southam Law charges flat fees, which means the costs for legal services are fixed in advance. This eliminates the shock of surprisingly high bills. Southam Law LLC also offers different levels of service for many cases."
    [params.feature.button]
      caption = "View success stories"
      url = "/work"

  [params.call]
    enable = true
    bgImage = "images/depaul-loop.jpg"
    title = "We do the things you need to"
    paragraph = "Southam Law LLC can help you with your immigration needs. We offer services for families, students, business, and other attorneys."
    [params.call.button]
      url = "../contact"
      text = "tell us your story"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Donâ€™t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      enabled = false
      note = "If you would like to contact us, fill out the form below and we will respond within a few business days."
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact information"
      address = "350 N Orleans St Ste 9000N Chicago IL 60654"
      email = "info@southamlaw.com"
      phone = "+1 773 466 4478"
      fax = "+1 773 409 5058"
      note = "(Please note that office hours are by appointment only)"
    [params.contact.gmaps]
      title = "Southam Law's home in Chicago"
      url = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2970.650847388626!2d-87.64512244923684!3d41.87885797324426!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2cc164bf57e1%3A0xa7583ae89d38c536!2sSoutham%20Law!5e0!3m2!1sen!2sus!4v1572195864812!5m2!1sen!2sus"
